### ISSUE TITLE
Problems with davical

### ISSUE THREAD

**Issue by U-Rise** [christian-putzke/Roundcube-CardDAV#12]
Hi Folks,

first thank you very much for writing the plugin to use carddav in roundcube, this is my first step to get rid of googlemail ;-)

Unfortunatly I have a problem to save contacts in the davical address book or even receive them. Once there is a contact in the davical db, carddav throws an internal server error. i use davical 1.0.2 debian.mcmillan.net.nz under debian squeeze with apache2 2.2.16-6+squeeze6, carddav graviox-Roundcube-CardDAV-22c47f3 with roundcube 0.5.4+dfsg-1~bpo60+1 from debian squeeze backports.

The logs said:
PHP Fatal error:  Call to undefined method rcube_vcard::get_assoc() in /var/lib/roundcube/plugins/carddav/carddav_addressbook.php on line 515

Any help is welcome! :o)

Regards,
U-Rise

**Comment by christian-putzke** [comment]
Hi U-Rise,
Roundcube CardDAV ist not supported for version 0.5.4 of Roundcube webmail. The minimum version of Roundcube webmail you have to install is version 0.6 because there is the extended addressbook included which is needed for my Roundcube CardDAV plugin.

Greetings,
Christian

**Comment by U-Rise** [comment]
Hi Christian,

thanx for the fast response, this is the answer I was afraid of ;-)
OK, then I will build my own deb package or install it just from the tar ball.

Regards,
Joris
