### ISSUE TITLE
Davical - xml response error

### ISSUE THREAD

**Issue by ghost** [christian-putzke/Roundcube-CardDAV#24]
I've managed to get other clients to connect to my Davical server, but I'm having problems getting the plugin to retrieve data from it.
It connects, as the log shows that it's connected, however I get:
"v0.5.1 | carddav_server_id 6 | CardDav-Server XML-Response is malformed. Synchronization aborted!"

I've tried outputting the response to the log, but it seems to come out blank.

I think I may have narrowed it down to contacts that are set to show as a company. I managed to get the other roundcube carddav client to sync after unsetting the contacts at which the sync was stopping from being set to company.
It seemed that the X-ABShowAs:COMPANY line in the vcard response was throwing an error. I will test this version when I get time to see if that is what is causing this plugin to fail. It is potentially down to me creating business contacts without adding an organization name.

**Comment by markuman** [comment]
Maybe this can solve you problem too at: https://github.com/graviox/Roundcube-CardDAV/issues/29
https://github.com/graviox/Roundcube-CardDAV/issues/29#issuecomment-7584813

> > Yes, the 3 lines with ">" replace the line with "<"
