### ISSUE TITLE
cronjob does not work

### ISSUE THREAD

**Issue by phsc84** [christian-putzke/Roundcube-CardDAV#31]
Hi

Whatever I try, I did not get cronjob to work.

Cronjob is set to:
1     \*   \*   \*  \*    /link/to/synchronize.php

Access rights for synchronize.php are '755'. 

I always get the following error:
/.../plugins/carddav/cronjob/synchronize.php: line 1: ?php: No such file or directory
/.../plugins/carddav/cronjob/synchronize.php: line 3: /-11.25-1333597966.tar.gz: Permission denied
/.../plugins/carddav/cronjob/synchronize.php: line 4: access-logs: command not found
/.../plugins/carddav/cronjob/synchronize.php: line 5: access-logs: command not found
/.../plugins/carddav/cronjob/synchronize.php: line 6: syntax error near unexpected token `newline`
/.../plugins/carddav/cronjob/synchronize.php: line 6: `* @author Christian Putzke <christian.putzke@graviox.de>`

My installation:
RoundCube 0.8rc
OwnCloud 4.0.6
PHP 5.4.5
Carddav Plugin 0.5.1

Thanks and regards

**Comment by daiw** [comment]
It is not possible to run a .php file as cronjob.
You have to start the php interpreter and give the file as an argument.

Something like this should work:
 1 \* \* \* \* /usr/bin/php /path/to/synchronize.php

If your php executable has an other path, you have to modify this statement.

Hope this helps

David

**Comment by phsc84** [comment]
Thank you very much! Now it works perfectly. :-)
