### ISSUE TITLE
CardDAV doesn't work with Roundcube 0.9-beta

### ISSUE THREAD

**Issue by Pantos** [christian-putzke/Roundcube-CardDAV#47]
Since Roundcube 0.9-beta CardDAV doesn't work. I always get this error:

PHP Fatal error:  Call to undefined method rcube_db_mysql::num_rows() in /is/htdocs/roundcubemail-0.9-beta/plugins/carddav/carddav.php on line 364

It seems there are new methods because of using PDO in Roundcube now. It would be fine if there could be an update for this nice plugin.

Thanks

Pantos

**Comment by Forumkel** [comment]
Same here, an update would be great!

**Comment by Pantos** [comment]
Now it works again in RC 0.9.1
