### ISSUE TITLE
Contacts don't show up

### ISSUE THREAD

**Issue by vandendal** [christian-putzke/Roundcube-CardDAV#5]
The connection to my davical server (Version: 1.0.2-1) seems to work but the addresses don't show up in roundcube.

The address count is shown in the bottomline and you can click a single entryline but it's nothing visible neither in the address list nor in the finegrain window.

I'm trying Roundcube-CardDAV version 0.2.6

cheers
vandendal

**Comment by christian-putzke** [comment]
Hi,
there is no 0.2.6 version from Roundcube-CardDAV but I think you mean 0.2.5 ;)
Which version of Roundcube do you use? Do you have installed all mysql-statements correctly or did you get any errors?

Greetings,
Christian

**Comment by vandendal** [comment]
Roundcube-CardDAV 0.2.5 (claro que sim, war spät)
roundcube 0.7.1-2 (debian testing)

The sql statements executed without errors.

cheers
vandendal

**Comment by christian-putzke** [comment]
I've released the new version v0.3. Please try the new version (don't forget the database updates and please readd your CardDAV-Servers) and let me know if you still have problems with my plugin.

**Comment by vandendal** [comment]
This looks good!

Adresses are shown and editable.

Thank you for the effort.
