### ISSUE TITLE
Birthday is reduced by one day at view/edit

### ISSUE THREAD

**Issue by ghost** [christian-putzke/Roundcube-CardDAV#6]
I am using the plugin (0.3) in combination with Roundcube 0.8-svn and Owncloud 3 stable. Each time I am viewing the personal information tab the birthday there is reduced by one day compared to the entry in owncloud's mysql database. Editing the contact and switching once again to the personal information tab again reduces the birthday by another day. After viewing, editing and saving, a contact ends up being two days younger.

**Comment by christian-putzke** [comment]
Hmm, that bug sounds strange. My plugin does not change any contact-data directly. It extends the adressbook from roundcube so that the bug maybe is a resultsfrom the unstable Roundcube version. Do you have tested that issue with the local Roundcube adressbook?

**Comment by ghost** [comment]
I just tested it with the local roundcube addressbook and have to say: you are right, the bug seems to be related to the unstable roundcube version. I am sorry about the noise and will check better next time.
