### ISSUE TITLE
No CardDAV settings in Settings->Addressbook (or settings period for that matter)

### ISSUE THREAD

**Issue by azfirefighter** [christian-putzke/Roundcube-CardDAV#65]
I've verified that the SQL statements made the correct additions to the database and have verified that the carddav is listed in the plugins array.  I've tried various combinations with $rcmail_config['address_book_type'] = 'sql';   I've tried sql, carddav and just leaving it blank, but there is still no option for carddav in my settings.  I'm quite frankly stumped.

I'm running Roundcube 0.9.5 with CardDAV version 0.5.1.   Any suggestions or a detailed fix would be appreciated.

**Comment by Philppe** [comment]
Hi,

I have the same problem.
There is an another post on this subject but I don't know if the person has managed to get a result :
https://github.com/graviox/Roundcube-CardDAV/issues/62

**Comment by azfirefighter** [comment]
Philppe

I managed to solve the issue by making sure the directory was owned by
the user that my web server was running as (both user and group) and
then making sure that both the web server user and group had rwx
permissions for the directory.
