### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by markuman** [christian-putzke/Roundcube-CardDAV#71]
As it looks like, it use the database connection from the roundcube setup (mysql or postgresql).
So running roundcube with sqlite backings is not supported now?

**Comment by lpapier** [comment]
You can try https://github.com/graviox/Roundcube-CardDAV/pull/73

**Comment by markuman** [comment]
Works like a charm!!!

I've applied the sqlite file with

```
    sqlite3 path/sqlite.db < plugins/carddav/SQL/sqlite.sql
```

**Comment by christian-putzke** [comment]
SQLite ist now supported. Thanks to lpapier!
