### ISSUE TITLE
readonly option

### ISSUE THREAD

**Issue by ghost** [christian-putzke/Roundcube-CardDAV#9]
I'd like to propose a readonly option (something like a checkbox during setup that could be unchecked later on). Some carddav clients don't work too well with the vcard format roundcube produces. The Mac OSX Lion Addressbook client e.g. can't handle edits done by roundcube and denies further syncing.

**Comment by christian-putzke** [comment]
Great idea! I'll implement it in the next major release.

**Comment by christian-putzke** [comment]
I've released the new major version 0.5 of Roundcube CardDAV. You feature request is included ;)
